import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` — see README
import 'config/emulator_config.dart';
import 'services/ads_service.dart';
import 'services/auth_service.dart';
import 'theme/app_theme.dart';
import 'screens/splash/splash_gate.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Startup steps are wrapped so that if ANYTHING here fails, you see the
  // actual error on your phone screen instead of the app just vanishing.
  // Temporary scaffolding for bringing up a real backend on a phone with
  // no computer to plug in and read logcat from — safe to remove once
  // startup is solid, but cheap enough to just leave in for now.
  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    connectToEmulatorsIfEnabled(); // must run before anything touches Auth/Firestore
    await AuthService.instance.ensureSignedIn(); // silent — no UI, no login screen
    await AdsService.instance.init();
    runApp(const TalkApp());
  } catch (error, stackTrace) {
    runApp(_StartupErrorApp(error: error, stackTrace: stackTrace));
  }
}

/// Shown only if startup itself throws. Plain, scrollable, copyable text —
/// screenshot this and it tells us exactly what's wrong, same as reading
/// a CI log, just from the phone instead.
class _StartupErrorApp extends StatelessWidget {
  const _StartupErrorApp({required this.error, required this.stackTrace});
  final Object error;
  final StackTrace stackTrace;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: const Color(0xFF1A0000),
        appBar: AppBar(
          backgroundColor: const Color(0xFF1A0000),
          title: const Text('Startup failed — screenshot this'),
        ),
        body: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: SelectableText(
            '$error\n\n$stackTrace',
            style: const TextStyle(color: Colors.white, fontFamily: 'monospace', fontSize: 12),
          ),
        ),
      ),
    );
  }
}

class TalkApp extends StatelessWidget {
  const TalkApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Talk',
      debugShowCheckedModeBanner: false,
      theme: buildAppTheme(),
      home: const SplashGate(),
      builder: (context, child) => _EmulatorBadge(child: child),
    );
  }
}

/// Small, unmissable-but-not-annoying reminder of which backend you're
/// hitting. Only ever renders when [useFirebaseEmulators] is true, so it
/// costs nothing in production and can't accidentally ship visible.
class _EmulatorBadge extends StatelessWidget {
  const _EmulatorBadge({required this.child});
  final Widget? child;

  @override
  Widget build(BuildContext context) {
    if (!useFirebaseEmulators || child == null) return child ?? const SizedBox.shrink();
    return Stack(
      children: [
        child!,
        Positioned(
          top: 0,
          right: 0,
          child: SafeArea(
            child: Container(
              margin: const EdgeInsets.only(right: 8, top: 4),
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
              decoration: BoxDecoration(
                color: Colors.orange.shade700,
                borderRadius: BorderRadius.circular(999),
              ),
              child: const Text(
                'EMULATOR',
                style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.w800),
              ),
            ),
          ),
        ),
      ],
    );
  }
}
